### ISSUE TITLE
appear errors when run cargo leptos watch -p lapa_admin 

### ISSUE THREAD

**Issue by wxyer** [alexichepura/lapa#31]
error[E0599]: no method named `view` found for struct `ForPropsBuilder` in the current scope

**Comment by alexichepura** [comment]
Thank you very much for the report!
I updated letptos and fixed this issue in the main branch.

**Comment by wxyer** [comment]
> Thank you very much for the report! I updated letptos and fixed this issue in the main branch.

thank you for your help,im beginer,
